### ISSUE TITLE
Inugami : Appliquer le nouveau style au menu principal

### ISSUE THREAD

**Issue by julgob** [inugamiio/inugami#73]
# CONTEXT
Afin d'appliquer le style voulu sur le menu principal, il faut créer des styles.
Il faut appliquer le nouveau style au menu principal:

# Nouveau rendu 
![ux](https://raw.githubusercontent.com/inugamiio/inugami-backlog/master/inugami/backlog/inugami-58_EPIC_ajout_alertes/design_02_low.jpg)

# Attendu
La charte graphique est appliquée sur la partie administration et l'intégralité d'inugami
On peut animer le menu admin

**Comment by pguillerm** [comment]
done in version 1.1.0
