### ISSUE TITLE
inugami : creation d'un service rest pour lister les data provider

### ISSUE THREAD

**Issue by julgob** [inugamiio/inugami#87]
### CONTEXT
Pour l'IHM de création d'alertes, on a besoin de la liste des data providers disponible dans le système. Cette liste servira à peupler une combo box avec les différents providers.

### API REST
```
[GET] http://{{ip/port}}/{{context}}/rest/provider
```
**Header :**

Attribute          | Value
-------------- | -------------
Content-Type  |  application/json
Authorization   |  Token 91c06246eab6cxxxxxxx

### MODEL
# Model
```javascript
[
    {
        "name": "providerName",
         "configurations": {
            "url": "https://my.provider.url",
            "max_connection": "20",
            "timeout": "5000",
            "ttl": "500",
            "max_per_route": "50",
            "socket_timeout": "5000"
        }
    }
]
```

**Comment by pguillerm** [comment]
done in version 1.1.0

**Comment by pguillerm** [comment]
done in version 1.1.0
